### ISSUE TITLE
Backend Deployment is failing 

### ISSUE THREAD

**Issue by abhishek-notes** [rpuls/medusajs-2.0-for-railway-boilerplate#11]
Logs from Railway for failing backend :  

 

#14 [stage-0 10/11] RUN printf '\nPATH=/app/node_modules/.bin:$PATH' >> /root/.profile

 

#14 DONE 0.9s

 

 

#15 [stage-0 11/11] COPY . /app

#15 DONE 0.1s

 

#16 exporting to image

#16 exporting layers

 

#16 exporting layers 14.8s done

 

#16 ...

 

 

#17 [auth] sharing credentials for us-west1.registry.rlwy.net

#17 DONE 0.0s

 

#16 exporting to image

#16 exporting manifest sha256:e89dd038620380b0da645eb10c7a446beb3d3e71316dc7324829d2fe0e45a355 done

#16 exporting config sha256:fd615d75524a901e22eb5cb520172f3d0705e957eaf1aacbf4f5c3217fb6a110 done

#16 exporting attestation manifest sha256:b143ffae2544e7bf5c19f688a530c72a6aa0b3ecd8b31074c32ad763ffee01bf 0.0s done

#16 exporting manifest list sha256:906f11b329e9a30eb5948146f621908ed0cc7b08f781ccfc5da16eb52d9aedb9 done

#16 pushing layers

 

#16 pushing layers 5.8s done

#16 pushing manifest for us-west1.registry.rlwy.net/960f5cf2-c415-4d63-9895-a3436d011241:786b48b9-6240-42f1-8aad-d348505d79a2@sha256:906f11b329e9a30eb5948146f621908ed0cc7b08f781ccfc5da16eb52d9aedb9

 

#16 pushing manifest for us-west1.registry.rlwy.net/960f5cf2-c415-4d63-9895-a3436d011241:786b48b9-6240-42f1-8aad-d348505d79a2@sha256:906f11b329e9a30eb5948146f621908ed0cc7b08f781ccfc5da16eb52d9aedb9 0.7s done

#16 DONE 21.4s

 

=== Successfully Built! ===

 

Run:

docker run -it us-west1.registry.rlwy.net/960f5cf2-c415-4d63-9895-a3436d011241:786b48b9-6240-42f1-8aad-d348505d79a2

 

Build time: 108.19 seconds

 

====================

Starting Healthcheck

====================

Path: /health

Retry window: 5m0s

 

Attempt #1 failed with service unavailable. Continuing to retry for 4m49s

Attempt #2 failed with service unavailable. Continuing to retry for 4m47s

Attempt #3 failed with service unavailable. Continuing to retry for 4m35s

Attempt #4 failed with service unavailable. Continuing to retry for 4m21s

Attempt #5 failed with service unavailable. Continuing to retry for 4m13s

Attempt #6 failed with service unavailable. Continuing to retry for 3m57s

Attempt #7 failed with service unavailable. Continuing to retry for 3m27s

Attempt #8 failed with service unavailable. Continuing to retry for 2m57s

Attempt #9 failed with service unavailable. Continuing to retry for 2m27s

Attempt #10 failed with service unavailable. Continuing to retry for 1m57s

Attempt #11 failed with service unavailable. Continuing to retry for 1m27s

Attempt #12 failed with service unavailable. Continuing to retry for 57s

Attempt #13 failed with service unavailable. Continuing to retry for 27s

 

1/1 replicas never became healthy!

Healthcheck failed!

**Comment by rpuls** [comment]
I just launched the template with no issue.
![image](https://github.com/user-attachments/assets/c7590977-12d4-45ae-9ae4-4eaca047454c)

I would suggest trying again ✌️

**Comment by abhishek-notes** [comment]
Thanks, it worked on re-trying after 2 times, it was railway's service.
