### ISSUE TITLE
Connecting to custom domain

### ISSUE THREAD

**Issue by compelinnovations** [rpuls/medusajs-2.0-for-railway-boilerplate#7]
When I connect a custom domain to Railway, I get a CORS error. 

...up.railway.app/auth/user/emailpass' from origin 'https://custom-domain' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by rpuls** [comment]
Hey ;) 

Are you getting this error when trying to login to your admin dashboard, after setting up custom domain on the backend container in Railway?

**Comment by compelinnovations** [comment]
Hi man, yes that is correct.

**Comment by rpuls** [comment]
Okay. I saw the same behavior as you. I can see that the request is made using the CORS setting from before the domain is setup. This is because during the build phase the medusa config is generated with the provided CORS settings, and at this point in time (before setup custom domain) they are some railway doamin.

So what I did to solve it, was to redeploy the backend after setting up the domain.

![image](https://github.com/user-attachments/assets/3073a43d-9679-44f9-93ab-b2462032d2eb)


Then the app will build again, but this time with the custom domain, and the medusa-config will be generated with the correct CORS url.

Please try this and let me know if you are able to login :)

**Comment by compelinnovations** [comment]
> Okay. I saw the same behavior as you. I can see that the request is made using the CORS setting from before the domain is setup. This is because during the build phase the medusa config is generated with the provided CORS settings, and at this point in time (before setup custom domain) they are some railway doamin.
> 
> So what I did to solve it, was to redeploy the backend after setting up the domain.
> 
> ![image](https://private-user-images.githubusercontent.com/14924038/381257862-3073a43d-9679-44f9-93ab-b2462032d2eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyNDE0OTIsIm5iZiI6MTczMDI0MTE5MiwicGF0aCI6Ii8xNDkyNDAzOC8zODEyNTc4NjItMzA3M2E0M2QtOTY3OS00NGY5LTkzYWItYjI0NjIwMzJkMmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDIyMzMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0ZWQwMmI5N2YwMGNjYjg3Y2JjMDhiNzhiNTUxZTAwNTFlYmE3ZDcwNWFhMjEwODlhYWI3NmI2ZWJmNmFjMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h-mEJt0TsbP8oE1dggvLAXOyya5eRmy_VApGHIJu_so)
> 
> Then the app will build again, but this time with the custom domain, and the medusa-config will be generated with the correct CORS url.
> 
> Please try this and let me know if you are able to login :)

This worked! Thank you.

**Comment by fydeos-alpha** [comment]
Sorry to dig up a closed issue, but I guess this is related. 

I had the same issue regarding CORS, and also did the same to redeploy, and the CORS errors were gone, all good so far.

However, I edited the variables to update the `MEDUSA_ADMIN_EMAIL` and the `MEDUSA_ADMIN_PASSWORD`, the medusa backend doesn't seem to honour this update. Now I am unable to sign in with the updated `MEDUSA_ADMIN_EMAIL`. 

Also the reset password doesn't seem to send out instruction email either, given the RESEND is properly configured.

In all, 2 issues:

 - Updating `MEDUSA_ADMIN_EMAIL` and `MEDUSA_ADMIN_PASSWORD` from variable will break sign in
 - Reset password feature in the backend doesn't seem to work, no email was sent, no error from the log

Any pointers would be helpful, cheers

**Comment by rpuls** [comment]
Hi
That's becuase `MEDUSA_ADMIN_EMAIL`  and `MEDUSA_ADMIN_PASSWORD` are only used when seeding the database, creating the very first required admin.

Once that has been done, you can invite other admins via the user section in the admin dashboard.

There is no reset password email by default in medusa - all automated emailing are opt-in and must be developed if needed. (I can see why you would expect this one to exist - but it doesn't unfortunately)

However,
I have created two examples to use as reference, those are the invite-user and order-confirmation [HERE](https://github.com/rpuls/medusajs-2.0-for-railway-boilerplate/tree/master/backend/src/modules/email-notifications/templates) with these two exmpales it should be possible to create other automated emails. There's also some documentation on how to do this here: 
[https://github.com/rpuls/medusajs-2.0-for-railway-boilerplate/tree/master/backend/src/modules/email-notifications](https://github.com/rpuls/medusajs-2.0-for-railway-boilerplate/tree/master/backend/src/modules/email-notifications)

Here's a little bit of good news: 
despite losing the credentials to your auto-generated admin users, there is still a way to create a new one without having to start all over.

1. get the connection string for your Railway database `DATABASE_URL` from the backend container variables.
2. On your local environment, add the value to /backend/.env `DATABASE_URL=<your-railway-db-url>`
3. Use the medusa cli to create a new admin user [command can be fount here](https://github.com/rpuls/medusajs-2.0-for-railway-boilerplate/tree/master/backend/src/modules/email-notifications/templates) 

Alternatively, if you have not spent hours on configuring your application - and do not have a lot of important data in your database, you can create a new databse very easily [see this video](https://youtu.be/6hKahRqL9YQ?si=Rgm9bHGo1JDLi5M7) it shows how to create a new database and re-seed it - so your admin user will be created with the values that you have changed.

Please let me know if any steps are unclear, then I can point you to additional resources that might be helpful. ✌️

**Comment by fydeos-alpha** [comment]
Thank you very much @rpuls, it's been very clear, all makes sense, cheers 🫶🏻
