### ISSUE TITLE
Error with resend

### ISSUE THREAD

**Issue by justinelut** [rpuls/medusajs-2.0-for-railway-boilerplate#9]
Am getting an error while trying to send emails that notification provider resend is not enabled 
![image](https://github.com/user-attachments/assets/1836ad20-955b-411a-851d-5cd00a6afac5)

**Comment by rpuls** [comment]
Hello. The system cannot send emails unless you integrate a email provider.
You can see how to setup Resend here: https://youtu.be/pbdZm26YDpE?si=_bLM7wsQYugVmlf2

**Comment by justinelut** [comment]
Managed to fix the issue, was due to double resend identifier on the database, thank you

**Comment by rpuls** [comment]
Glad to hear it worked out! :)
